notifications:
    - email: false

before_install:
    - openssl aes-256-cbc -K $encrypted_481248b6289f_key -iv $encrypted_481248b6289f_iv -in .travis.id_rsa.enc -out id_rsa -d

install:
    - make install TRAVIS=true

script:
    - make lint

after_success:
    - chmod 600 id_rsa
    - git remote add deploy travis@somasis.com:/srv/www/wiki.somasis.com
    - GIT_SSH_COMMAND='ssh -i id_rsa -o StrictHostKeyChecking=no' git push deploy -vf
